@extends('layouts.vali')

@section('content')
<style>
    div, h1, h2, h3, h4, h5, h6, p, a, span, label, input, select, textarea, button, .breadcrumb, .card-header, .card-footer {
        font-family: 'Century Gothic', sans-serif !important;
    }
</style>
<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Record Expense</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="#">Dashboard</a></li>
                    <li><a href="{{ route('accountant.expenses.index') }}">Expenses</a></li>
                    <li class="active">Add New</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="content mt-3">
    <div class="card">
        <div class="card-header">
            <strong>New Expense Entry</strong>
        </div>
        <div class="card-body card-block">
            <form action="{{ route('accountant.expenses.store') }}" method="post" enctype="multipart/form-data" class="form-horizontal">
                @csrf
                
                <!-- Date -->
                <div class="row form-group">
                    <div class="col col-md-3"><label for="date" class=" form-control-label">Date</label></div>
                    <div class="col-12 col-md-9">
                        <input type="date" id="date" name="date" value="{{ date('Y-m-d') }}" class="form-control" required>
                    </div>
                </div>

                <!-- Expense Category -->
                <div class="row form-group">
                    <div class="col col-md-3"><label for="expense_category" class=" form-control-label">Expense Category</label></div>
                    <div class="col-12 col-md-9">
                        <select name="expense_category" id="expense_category" class="form-control" required>
                            <option value="">Please select</option>
                            @foreach($categories as $category)
                                <option value="{{ $category['name'] }}" data-remaining="{{ $category['remaining'] }}">{{ $category['name'] }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <!-- Voucher Type -->
                <div class="row form-group">
                    <div class="col col-md-3"><label class=" form-control-label">Voucher Type</label></div>
                    <div class="col col-md-9">
                        <div class="form-check-inline form-check">
                            <label for="voucher_petty" class="form-check-label mr-4">
                                <input type="radio" id="voucher_petty" name="voucher_type" value="Petty Cash Voucher" class="form-check-input" checked onchange="toggleAccountOptions()"> Petty Cash Voucher
                            </label>
                            <label for="voucher_payment" class="form-check-label">
                                <input type="radio" id="voucher_payment" name="voucher_type" value="Payment Voucher" class="form-check-input" onchange="toggleAccountOptions()"> Payment Voucher
                            </label>
                        </div>
                    </div>
                </div>

                <!-- Payment Account -->
                <div class="row form-group">
                    <div class="col col-md-3"><label for="payment_account" class=" form-control-label">Payment Account</label></div>
                    <div class="col-12 col-md-9">
                        <select name="payment_account" id="payment_account" class="form-control" required>
                            <option value="Cash">Cash</option> <!-- Default for Petty Cash -->
                        </select>
                    </div>
                </div>

                <!-- Voucher Number Preview -->
                <div class="row form-group">
                    <div class="col col-md-3"><label class=" form-control-label">Voucher Number</label></div>
                    <div class="col-12 col-md-9">
                        <p class="form-control-static text-muted" id="voucher_preview">{{ $voucherPreview }}</p>
                        <small class="form-text text-muted">Auto-generated by system</small>
                    </div>
                </div>

                <!-- Description -->
                <div class="row form-group">
                    <div class="col col-md-3"><label for="description" class=" form-control-label">Description</label></div>
                    <div class="col-12 col-md-9">
                        <textarea name="description" id="description" rows="3" placeholder="Enter expense details..." class="form-control"></textarea>
                    </div>
                </div>

                <!-- Amount -->
                <div class="row form-group">
                    <div class="col col-md-3"><label for="amount" class=" form-control-label">Amount</label></div>
                    <div class="col-12 col-md-9">
                        <input type="number" id="amount" name="amount" placeholder="0.00" class="form-control" required min="1" step="0.01">
                    </div>
                </div>

                <!-- Attachment -->
                <div class="row form-group">
                    <div class="col col-md-3"><label for="attachment" class=" form-control-label">Attachment (Optional)</label></div>
                    <div class="col-12 col-md-9">
                        <input type="file" id="attachment" name="attachment" class="form-control-file">
                    </div>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                    <button type="reset" class="btn btn-danger btn-sm">
                        <i class="fa fa-ban"></i> Reset
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const amountInput = document.getElementById('amount');
        const categorySelect = document.getElementById('expense_category');

        function checkBudget() {
            const amount = parseFloat(amountInput.value);
            const selectedOption = categorySelect.options[categorySelect.selectedIndex];

            if (!selectedOption.value || isNaN(amount)) return;

            const remaining = parseFloat(selectedOption.getAttribute('data-remaining'));
            
            // Logic: If user enters an amount > remaining budget, show alert.
            // Note: If remaining is 0, it might trigger every time if budget wasn't set (which is effectively 0).
            if (!isNaN(remaining) && amount > remaining) {
                Swal.fire({
                    icon: 'warning',
                    title: 'Budget Low!',
                    text: 'The entered amount (' + amount.toLocaleString() + ') exceeds the remaining budget (' + remaining.toLocaleString() + ') for ' + selectedOption.text + '.',
                    confirmButtonColor: '#ffc107',
                    confirmButtonText: 'OK, I Understand'
                });
            }
        }

        // Trigger check when amount changes or category changes
        amountInput.addEventListener('change', checkBudget);
        categorySelect.addEventListener('change', checkBudget);
    });

    function toggleAccountOptions() {
        var voucherType = document.querySelector('input[name="voucher_type"]:checked').value;
        var accountSelect = document.getElementById('payment_account');
        var voucherPreview = document.getElementById('voucher_preview');
        var currentYear = new Date().getFullYear();
        
        // Clear options
        accountSelect.innerHTML = '';
        
        if (voucherType === 'Petty Cash Voucher') {
            // Add Cash option
            var option = document.createElement('option');
            option.value = 'Cash';
            option.text = 'Cash';
            option.selected = true;
            accountSelect.add(option);
            // Lock selection if needed, or just leave as single option
            
            // Update preview roughly (real number generated on server)
            voucherPreview.innerText = "PCV-" + currentYear + "-XXX";
        } else {
            // Add Bank options
            var accounts = ['CRDB', 'NMB', 'NBC', 'Mobile Money'];
            accounts.forEach(function(acc) {
                var option = document.createElement('option');
                option.value = 'Bank - ' + acc;
                option.text = 'Bank - ' + acc;
                accountSelect.add(option);
            });
            
             voucherPreview.innerText = "PV-" + currentYear + "-XXX";
        }
    }
</script>
@endsection
